CREATE TABLE roles (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(60) NOT NULL UNIQUE,
    name          VARCHAR(120) NOT NULL,
    email         VARCHAR(180) NOT NULL UNIQUE,
    password      VARCHAR(100) NOT NULL,
    date_of_birth DATE NOT NULL,
    role_id       BIGINT NOT NULL,
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE INDEX idx_users_role_id ON users (role_id);

INSERT INTO roles (role_name) VALUES ('ADMIN'), ('TRAINER'), ('TRAINEE');