CREATE TABLE courses (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(150) NOT NULL UNIQUE,
    capacity   INT NOT NULL,
    trainer_id BIGINT NOT NULL,
    CONSTRAINT fk_courses_trainer FOREIGN KEY (trainer_id) REFERENCES trainers (id)
);

CREATE TABLE enrollments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainee_id  BIGINT NOT NULL,
    course_id   BIGINT NOT NULL,
    enrolled_on DATE NOT NULL,
    CONSTRAINT fk_enrollments_trainee FOREIGN KEY (trainee_id) REFERENCES trainees (id),
    CONSTRAINT fk_enrollments_course  FOREIGN KEY (course_id)  REFERENCES courses (id),
    CONSTRAINT uk_enrollments_trainee_course UNIQUE (trainee_id, course_id)
);

CREATE INDEX idx_enrollments_course_id ON enrollments (course_id);